# Simple playbook to install Docker, make docker group and run hello-world container.
---
- name: Install Docker
  hosts: test_servers
  become: yes

  tasks:
  - name: Install Necessary Packages
    apt:
       pkg: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - virtualenv 

  - name: Add key
    apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

  - name: Add repository
    apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

  - name: Update apt and Install docker
    apt:
       name: docker-ce
       state: latest
       update_cache: true

  - name: Add docker group
    group: 
       name: docker

  - name: Add user to the group
    user: 
      name: "{{ ansible_user }}"
      group: docker

  - name: Install Docker Module for Python
    pip:
       name: docker

  - name: Run Hello World container
    docker_container:
      name: hello-world
      image: library/hello-world
