
---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes


  vars:
    src_file: ./index.html
    dest_file: /var/www/html


  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy Index html from source server
    copy: src={{ src_file }} dest={{ dest_file }} mode=0555
    notify: Restart Apache

  - name: Start and Enable Apache Web Server
    service: name=apache2 state=started enabled=yes


  handlers:
  - name: Restart Apache 
    service: name=apache2 state=restarted
  
