# Simple playbook to reboot all specified servers
---
- name: playbook to reboot some servers
  hosts: "{{ my_hosts }}"
  become: yes
  
  tasks:
  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till server will come up online
    wait_for:
        host: "{{ inventory_hostname}}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
